### PR TITLE
Port to ROS2

### PR DESCRIPTION
**Pull request by ijnek**
Note that this PR aims to preserve functionality from ROS1, but is almost built ground up since some ROS1 functionality heavily used (like nodelets) are gone in ROS2.

Still left to:
- [x] throttle_repeated_barcodes

### CODE REVIEW

**Comment by ijnek** [comment]
@paulbovbel Has been a while, but finally got around to porting the throttling function across. Ready for review.

**Comment by ijnek** [comment]
Hi @paulbovbel , a gentle ping on this PR.

**Comment by paulbovbel** [comment]
Thanks! Would you like to add yourself as an author and/or maintainer?

**Comment by ijnek** [comment]
@paulbovbel That's fine with me, I'll update the package.xml with my info and would you be able to give me developer or maintainer access to the repo? Thanks.

**Comment by ijnek** [comment]
@paulbovbel I've added myself as the maintainer

**Pull request merged**
